export const FORM_NAME = {
  // Monday
  MON_ALLDAY_OPEN: 'mon-all_day-open',
  MON_ALLDAY_CLOSE: 'mon-all_day-close',
  MON_MORNING_OPEN: 'mon-morning-open',
  MON_MORNING_CLOSE: 'mon-morning-close',
  MON_LUNCH_OPEN: 'mon-lunch-open',
  MON_LUNCH_CLOSE: 'mon-lunch-close',
  MON_DINNER_OPEN: 'mon-dinner-open',
  MON_DINNER_CLOSE: 'mon-dinner-close',
  MON_BAR_OPEN: 'mon-bar-open',
  MON_BAR_CLOSE: 'mon-bar-close',

  // Tuesday
  TUE_ALLDAY_OPEN: 'tue-all_day-open',
  TUE_ALLDAY_CLOSE: 'tue-all_day-close',
  TUE_MORNING_OPEN: 'tue-morning-open',
  TUE_MORNING_CLOSE: 'tue-morning-close',
  TUE_LUNCH_OPEN: 'tue-lunch-open',
  TUE_LUNCH_CLOSE: 'tue-lunch-close',
  TUE_DINNER_OPEN: 'tue-dinner-open',
  TUE_DINNER_CLOSE: 'tue-dinner-close',
  TUE_BAR_OPEN: 'tue-bar-open',
  TUE_BAR_CLOSE: 'tue-bar-close',

  // Wednesday
  WED_ALLDAY_OPEN: 'wed-all_day-open',
  WED_ALLDAY_CLOSE: 'wed-all_day-close',
  WED_MORNING_OPEN: 'wed-morning-open',
  WED_MORNING_CLOSE: 'wed-morning-close',
  WED_LUNCH_OPEN: 'wed-lunch-open',
  WED_LUNCH_CLOSE: 'wed-lunch-close',
  WED_DINNER_OPEN: 'wed-dinner-open',
  WED_DINNER_CLOSE: 'wed-dinner-close',
  WED_BAR_OPEN: 'wed-bar-open',
  WED_BAR_CLOSE: 'wed-bar-close',

  // Thursday
  THU_ALLDAY_OPEN: 'thu-all_day-open',
  THU_ALLDAY_CLOSE: 'thu-all_day-close',
  THU_MORNING_OPEN: 'thu-morning-open',
  THU_MORNING_CLOSE: 'thu-morning-close',
  THU_LUNCH_OPEN: 'thu-lunch-open',
  THU_LUNCH_CLOSE: 'thu-lunch-close',
  THU_DINNER_OPEN: 'thu-dinner-open',
  THU_DINNER_CLOSE: 'thu-dinner-close',
  THU_BAR_OPEN: 'thu-bar-open',
  THU_BAR_CLOSE: 'thu-bar-close',

  // Friday
  FRI_ALLDAY_OPEN: 'fri-all_day-open',
  FRI_ALLDAY_CLOSE: 'fri-all_day-close',
  FRI_MORNING_OPEN: 'fri-morning-open',
  FRI_MORNING_CLOSE: 'fri-morning-close',
  FRI_LUNCH_OPEN: 'fri-lunch-open',
  FRI_LUNCH_CLOSE: 'fri-lunch-close',
  FRI_DINNER_OPEN: 'fri-dinner-open',
  FRI_DINNER_CLOSE: 'fri-dinner-close',
  FRI_BAR_OPEN: 'fri-bar-open',
  FRI_BAR_CLOSE: 'fri-bar-close',

  // Saturday
  SAT_ALLDAY_OPEN: 'sat-all_day-open',
  SAT_ALLDAY_CLOSE: 'sat-all_day-close',
  SAT_MORNING_OPEN: 'sat-morning-open',
  SAT_MORNING_CLOSE: 'sat-morning-close',
  SAT_LUNCH_OPEN: 'sat-lunch-open',
  SAT_LUNCH_CLOSE: 'sat-lunch-close',
  SAT_DINNER_OPEN: 'sat-dinner-open',
  SAT_DINNER_CLOSE: 'sat-dinner-close',
  SAT_BAR_OPEN: 'sat-bar-open',
  SAT_BAR_CLOSE: 'sat-bar-close',

  // Sunday
  SUN_ALLDAY_OPEN: 'sun-all_day-open',
  SUN_ALLDAY_CLOSE: 'sun-all_day-close',
  SUN_MORNING_OPEN: 'sun-morning-open',
  SUN_MORNING_CLOSE: 'sun-morning-close',
  SUN_LUNCH_OPEN: 'sun-lunch-open',
  SUN_LUNCH_CLOSE: 'sun-lunch-close',
  SUN_DINNER_OPEN: 'sun-dinner-open',
  SUN_DINNER_CLOSE: 'sun-dinner-close',
  SUN_BAR_OPEN: 'sun-bar-open',
  SUN_BAR_CLOSE: 'sun-bar-close',
} as const;
