services:
  db:
    image: postgres:17
    container_name: postgres
    environment:
      - TZ=America/Vancouver
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

  memcached:
    image: memcached:1
    container_name: memcached
    ports:
      - '11211:11211'
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
